Bugfix RegistrationError: <Model> has not been registered with django-reversion
Just skip all relation fields, that point to a not registered model.
Because there is no history information for building a diff ;)

e.g.:
```
...
File "/home/jens/repos/django-reversion-compare/reversion_compare/compare.py", line 300, in
changed
    info = self.get_m2o_change_info()
File "/home/jens/repos/django-reversion-compare/reversion_compare/compare.py", line 333, in
get_m2o_change_info
    m2o_data1, m2o_data2 = self.get_reverse_foreign_key()
File "/home/jens/repos/django-reversion-compare/reversion_compare/compare.py", line 327, in
get_reverse_foreign_key
    return self.compare_obj1.get_reverse_foreign_key(), self.compare_obj2.get_reverse_foreign_key()
File "/home/jens/repos/django-reversion-compare/reversion_compare/compare.py", line 156, in
get_reverse_foreign_key
    return self.get_many_to_something(ids, related_model, is_reverse=True)
File "/home/jens/repos/django-reversion-compare/reversion_compare/compare.py", line 209, in
get_many_to_something
    missing_objects_dict = {
File "/home/jens/repos/django-reversion-compare/reversion_compare/compare.py", line 212, in
<dictcomp>
    for ver in Version.objects.get_for_object(o)
File
"/home/jens/repos/django-reversion-compare/.tox/py310-django32/lib/python3.10/site-packages/django/db/models/manager.py",
line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
File
"/home/jens/repos/django-reversion-compare/.tox/py310-django32/lib/python3.10/site-packages/reversion/models.py",
line 136, in get_for_object
    return self.get_for_object_reference(obj.__class__, obj.pk, model_db=model_db)
File
"/home/jens/repos/django-reversion-compare/.tox/py310-django32/lib/python3.10/site-packages/reversion/models.py",
line 131, in get_for_object_reference
    return self.get_for_model(model, model_db=model_db).filter(
File
"/home/jens/repos/django-reversion-compare/.tox/py310-django32/lib/python3.10/site-packages/reversion/models.py",
line 124, in get_for_model
    content_type = _get_content_type(model, self.db)
File
"/home/jens/repos/django-reversion-compare/.tox/py310-django32/lib/python3.10/site-packages/reversion/revisions.py",
line 432, in _get_content_type
    version_options = _get_options(model)
File
"/home/jens/repos/django-reversion-compare/.tox/py310-django32/lib/python3.10/site-packages/reversion/revisions.py",
line 418, in _get_options
    _assert_registered(model)
File
"/home/jens/repos/django-reversion-compare/.tox/py310-django32/lib/python3.10/site-packages/reversion/revisions.py",
line 412, in _assert_registered
    raise RegistrationError("{model} has not been registered with django-reversion".format(
reversion.errors.RegistrationError: <class 'reversion_compare_project.models.NotRegisteredModel'>
has not been registered with django-reversion

```